# Generated by Django 3.1 on 2021-01-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210109_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in process', 'In process'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
